const types = {
  // auth action types
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  LOGGING_OUT: 'LOGGING_OUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'LOGOUT_FAIL',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',

  // pomodoro timer and selection action types
  FOCUS_SESSION_START: 'FOCUS_SESSION_START',
  FOCUS_SESSION_COMPLETE: 'FOCUS_SESSION_COMPLETE',
  FOCUS_SESSION_EXTENDED: 'FOCUS_SESSION_EXTENDED',
  BREAK_SESSION_START: 'BREAK_SESSION_START',
  BREAK_SESSION_COMPLETE: 'BREAK_SESSION_COMPLETE',
  DEFAULT: 'DEFAULT',
  SELECTED_FOCUS_TIME: 'SELECTED_FOCUS_TIME',
  SELECTED_BREAK_TIME: 'SELECTED_BREAK_TIME',

  // pomodoro events api request action types
  GETTING_EVENT: 'GETTING_EVENT',
  GOT_EVENT: 'GOT_EVENT',
  GET_EVENT_FAIL: 'GET_EVENT_FAIL',
  WEEKLY_UPDATING: 'WEEKLY_UPDATING',
  WEEKLY_UPDATED: 'WEEKLY_UPDATED',
  WEEKLY_FAIL: 'WEEKLY_FAIL',
  SESSION_UPDATING: 'SESSION_UPDATING',
  SESSION_UPDATED: 'SESSION_UPDATED',
  SESSION_UPDATE_FAIL: 'SESSION_UPDATE_FAIL',
  
  // user pomodoro stats api request action types
  GETTING_BERRIES_COUNT: 'GETTING_BERRIES_COUNT',
  GOT_BERRIES_COUNT: 'GOT_BERRIES_COUNT',
  GET_BERRIES_COUNT_FAIL: 'GET_BERRIES_COUNT_FAIL',
  GETTING_WEEKLY_GRAPH: 'GETTING_WEEKLY_GRAPH',
  GOT_WEEKLY_GRAPH: 'GOT_WEEKLY_GRAPH',
  GET_WEEKLY_FAIL: 'GET_WEEKLY_FAIL',
};

export default types;